Pharmaderm/Pharmaderm-war/src/java/com/pharmaderm/controller/managedBean/DebtorsController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pharmaderm.controller.managedBean;

import com.pharmaderm.entities.Debtors;
import com.pharmaderm.session.PharmadermSessionBean;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.ArrayDataModel;
import javax.faces.model.DataModel;
import org.primefaces.event.RowEditEvent;

/**
 *
 * @author Abdul-Rahman Sudais
 */
@ManagedBean
@SessionScoped
public class DebtorsController implements Serializable {

    @EJB
    PharmadermSessionBean pharmadermSessionBean;
    Debtors debtors;
    DataModel<Debtors> debtorsDataModel = new ArrayDataModel<Debtors>();
    private double total;
    private double unit_p;
    private double balance_rem;
    private int qty;
    private double part_pay;
    private int t_qty = 0;
    private double t_amt = 0.0 , bal_rem = 0.0;
    private double t_part_pay = 0.0;

    public void saveDebtorsData() {
        try {
            String d_id = UUID.randomUUID().toString().substring(0, 6);
            total = qty * unit_p;
            balance_rem = total - part_pay;
            debtors.setCompId(d_id);
            debtors.setBalRem(balance_rem);
            debtors.setDateBought(new Date());
            debtors.setPartPay(part_pay);
            debtors.setTotalPrice(total);
            debtors.setQtySupplied(qty);
            debtors.setUnitPrice(unit_p);
            debtors.setStatus("Part-payed");
            pharmadermSessionBean.createDebtor(debtors);
            setDebtors(new Debtors());
            setPart_pay(0.0);
            setUnit_p(0.0);
            setQty(0);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("not created!!");
        }
    }

    public List<Debtors> getFindDebtorsGetAll() {
        try {
            return pharmadermSessionBean.debtorsListGetAll();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void updateDetors() {
        try {
            debtors.setStatus("Completed");
            debtors.setPartPay(0.0);
            debtors.setBalRem(0.0);
            debtors.setDateBought(new Date());
            pharmadermSessionBean.debtorUpdate(debtors);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Successfully Updated");
        }
    }

    public void reset() {
        setDebtors(new Debtors());
        setPart_pay(0.0);
        setUnit_p(0.0);
        setQty(0);
        setTotal(0.0);
        setBalance_rem(0.0);
    }

    public void onRowEditDrugsInfoData(RowEditEvent event) {
        try {
            debtors = (Debtors) event.getObject();
            boolean update = pharmadermSessionBean.debtorUpdate(debtors);
            if (update) {
                FacesMessage mge = new FacesMessage("Item Updated for  ", ((Debtors) event.getObject()).getItemName());
                FacesContext.getCurrentInstance().addMessage(null, mge);
                System.out.println("Updated successfully!!");
            } else {
                FacesMessage mge = new FacesMessage("Item Cannot be Updated for  ", ((Debtors) event.getObject()).getItemName());
                FacesContext.getCurrentInstance().addMessage(null, mge);
                System.out.println("Unable to update item Info");
            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Unable to update!!  " + e.getMessage());
        }
    }

    public void processDataItems() {
        debtors = debtorsDataModel.getRowData();
    }

    public List<Debtors> getDebtorsALl() {
        try {
            return pharmadermSessionBean.debtorsListGetAll();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public DebtorsController() {
        debtors = new Debtors();
    }

    public DataModel<Debtors> getDebtorsDataModel() {
        return debtorsDataModel;
    }

    public void setDebtorsDataModel(DataModel<Debtors> debtorsDataModel) {
        this.debtorsDataModel = debtorsDataModel;
    }

    public int getT_qty() {
        t_qty = 0;
        for (Debtors deb1 : getDebtorsALl()) {
            t_qty += deb1.getQtySupplied();
        }
        return t_qty;
    }

    public void setT_qty(int t_qty) {
        this.t_qty = t_qty;
    }

    public double getT_amt() {
        t_amt = 0.0;
        for (Debtors debtors1 : getDebtorsALl()) {
            t_amt += debtors1.getTotalPrice();
        }
        return t_amt;
    }

    public double getBal_rem() {
        bal_rem = 0.0;
        for (Debtors debt : getDebtorsALl()) {
            bal_rem += debt.getBalRem();
        }
        return bal_rem;
    }

    public void setBal_rem(double bal_rem) {
        this.bal_rem = bal_rem;
    }

    public void setT_amt(double t_amt) {
        this.t_amt = t_amt;
    }

    public double getT_part_pay() {
        t_part_pay = 0.0;
        for (Debtors deb : getDebtorsALl()) {
            t_part_pay += deb.getPartPay();
        }
        return t_part_pay;
    }

    public void setT_part_pay(double t_part_pay) {
        this.t_part_pay = t_part_pay;
    }

    public PharmadermSessionBean getPharmadermSessionBean() {
        return pharmadermSessionBean;
    }

    public void setPharmadermSessionBean(PharmadermSessionBean pharmadermSessionBean) {
        this.pharmadermSessionBean = pharmadermSessionBean;
    }

    public Debtors getDebtors() {
        return debtors;
    }

    public void setDebtors(Debtors debtors) {
        this.debtors = debtors;
    }

    public double getTotal() {
        return total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public double getUnit_p() {
        return unit_p;
    }

    public void setUnit_p(double unit_p) {
        this.unit_p = unit_p;
    }

    public double getBalance_rem() {
        return balance_rem;
    }

    public void setBalance_rem(double balance_rem) {
        this.balance_rem = balance_rem;
    }

    public int getQty() {
        return qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    public double getPart_pay() {
        return part_pay;
    }

    public void setPart_pay(double part_pay) {
        this.part_pay = part_pay;
    }
}

Pharmaderm/Pharmaderm-war/src/java/com/pharmaderm/controller/managedBean/StockController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pharmaderm.controller.managedBean;

import com.pharmaderm.entities.Counter;
import com.pharmaderm.entities.DrugsReturned;
import com.pharmaderm.entities.Sales;
import com.pharmaderm.entities.SupplyReturn;
import com.pharmaderm.session.PharmadermSessionBean;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.ConverterException;
import javax.faces.model.ArrayDataModel;
import javax.faces.model.DataModel;
import javax.faces.model.SelectItem;
import org.primefaces.event.RowEditEvent;

/**
 *
 * @author Abdul-Rahman Sudais
 */
@ManagedBean
@SessionScoped
public class StockController implements Serializable {

    /**
     * Creates a new instance of StockController
     */
    @EJB
    PharmadermSessionBean pharmadermSessionBean;
    Counter counter;
    Sales sales;
    DrugsReturned drugsReturned;
    SupplyReturn supplyReturn;
    List<Counter> listOfCounters = new ArrayList<Counter>();
    List<Counter> counterList = new ArrayList<Counter>();
    DataModel<Counter> dataModelCounter = new ArrayDataModel<Counter>();
    SelectItem[] counterSelect;
    SelectItem[] salesSelect;
    private Integer quantity;
    private String drugName;
    private Double pric;
    private Double net_amount;
    private Date expire;
    private Integer qty_dis;
    private Double total = 0.0;
    private Date salesDate, dis_date;
    private int total_sales_quantity = 0, dis_total = 0;
    private double total_sales_amount = 0.0, single_amount = 0.0, general_amount = 0.0, total_cost_amount = 0.0, single_cost_amount = 0.0, general_cost_amount = 0.0, single_profit, general_profit, total_sales_profit = 0.0;
    private int daily_quantity = 0, single_quantity = 0, general_quantity = 0;
    private double daily_amount = 0.0;
    private boolean print_report = false;
    private Date stDate;
    private Date endDate;
    private int tabIndex = 1;
    private boolean recp = true;
    private boolean printre = false;
    private CounterConvertor counterConvertor = new CounterConvertor();
    private Double cost_price, cost_amount;
    private Double daily_cost_amount = 0.0, daily_profit = 0.0;
    private String message = "";
    private Double amount_paid, balance;

    public void saveStock() {
        try {
            String UUIString = UUID.randomUUID().toString().substring(0, 5);
            counter.setCounterId(UUIString);
            counter.setDeleted("NO");
            counter.setDistributionDate(new Date());
            pharmadermSessionBean.CounterCreate(counter);
            setCounter(new Counter());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearStock() {
        setCounter(new Counter());
    }

    public List<Counter> getAllCounterDrugs() {
        try {
            return pharmadermSessionBean.counterGetAll();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public List<Counter> getCounterDrugsAll() {
        try {
            return pharmadermSessionBean.counterGetAll();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Not available!1");
            return null;
        }
    }

    public void firstTab() {
        tabIndex = 0;
    }

    public void secondTab() {
        tabIndex = 2;
    }

    public List<Sales> getSalesInfo() {
        try {
            return pharmadermSessionBean.salesGetAll();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public String maintainPage() {
        print_report = true;
        return "day.xhtml";
    }

    public void loadDrugsForSelection() {
        counterConvertor.allDrugs();
        counterList = counterConvertor.counteree;
    }

    public List<Counter> completeDrugName(String query) {
        List<Counter> autoComp = new ArrayList<Counter>();
        for (Iterator<Counter> it = counterList.iterator(); it.hasNext();) {
            Counter s = it.next();
            if (s.getDrugName().toLowerCase().startsWith(query.toLowerCase()) && !autoComp.contains(s)) {

                autoComp.add(s);

            } else {
            }
        }

        return autoComp;

    }

    public String displayInfoPage() {
        firstTab();
        print_report = true;
        return "report.xhtml";
    }

    public String general() {
        firstTab();
        print_report = true;
        return "general.xhtml";
    }

    public List<Sales> getAllSalesByDay() {
        try {
            return pharmadermSessionBean.findByDayReportType(salesDate);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void onRowEditDrugsInfo(RowEditEvent event) {
        try {
            counter = (Counter) event.getObject();
            boolean update = pharmadermSessionBean.counterUpdate(counter);
            if (update) {
                FacesMessage mge = new FacesMessage("Drug Updated for  ", ((Counter) event.getObject()).getDrugName());
                FacesContext.getCurrentInstance().addMessage(null, mge);
                System.out.println("Updated successfully!!");
            } else {
                FacesMessage mge = new FacesMessage("Drug Cannot be Updated for  ", ((Counter) event.getObject()).getDrugName());
                FacesContext.getCurrentInstance().addMessage(null, mge);
                System.out.println("Unable to update drug Info");
            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Unable to update!!");
        }
    }

    public List<Sales> getSingleDrugReport() {
        try {
            return pharmadermSessionBean.findBySingleDrug(drugName, stDate, endDate);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    class CounterConvertor implements Converter {

        public List<Counter> counteree = new ArrayList<Counter>();

        public void allDrugs() {
            counteree = pharmadermSessionBean.counterGetAll();
        }

        @Override
        public Object getAsObject(FacesContext context, UIComponent component, String submittedValue) {

            if (submittedValue.trim().equals("")) {
                return null;
            } else {
                try {
                    //int number = Integer.parseInt(submittedValue);  

                    for (Counter s : counteree) {
                        if (s.getCounterId().equals(submittedValue)) {
                            return s;
                        }
                    }

                } catch (NumberFormatException exception) {
                    throw new ConverterException(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Conversion Error", "Not a valid Drug!!"));
                }
            }

            return null;
        }

        @Override
        public String getAsString(FacesContext context, UIComponent component, Object value) {
            if (value == null || value.equals("")) {
                return "";
            } else {
                return String.valueOf(((Counter) value).getCounterId());
            }

        }
    }

    public List<Sales> getGeneralRportOnSales() {
        try {
            return pharmadermSessionBean.generalSalesQuery(stDate, endDate);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void addList() {
        try {
            String Ui = UUID.randomUUID().toString().substring(0, 4);
            counter.setCounterId(Ui);
            counter.setDrugQuantity(quantity);
            counter.setPrice(net_amount);
            counter.setCostPrice(cost_amount);
            if (net_amount <= 0) {
                message = " Please Quantity is greater than that in stock for drug " + counter.getDrugName();
            } else {
                message = "";
                listOfCounters.add(counter);
                total += net_amount;
                Date ddd = counter.getExpiryDate();
                Long dt = ddd.getTime();
                Date to = new Date();
                Long de = to.getTime();
                int days = (int) ((dt - de) / 1000);
                int realDays = (days / 86400);
                FacesMessage facesMessage = new FacesMessage(realDays + "  Days More for  " + counter.getDrugName() + "  to Expire.!! ");
                facesMessage.setSeverity(FacesMessage.SEVERITY_INFO);
                FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                setCounter(new Counter());
                setDrugName("");
                setQuantity(0);
                setQty_dis(0);
                setNet_amount(0.0);
                setPric(0.0);
                setCost_amount(0.0);
            }
        } catch (Exception e) {
            System.out.println("Not available");
            e.printStackTrace();
        }
    }

    public List<Counter> getCounterDrugsByDates() {
        try {
            return pharmadermSessionBean.findByDates(dis_date);
        } catch (Exception e) {
            System.out.println("Unable to find!!");
            e.printStackTrace();
        }
        return null;
    }

    public void calculateChange() {
        try {
            balance = amount_paid - total;
        } catch (Exception e) {
            System.out.println("Error Occured in getting balance: " + e.getLocalizedMessage());
        }
    }

Pharmaderm/Pharmaderm-war/web/change_2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>change -pass</title>
    </h:head>
    <h:body>
   
        <ui:composition template="both.xhtml">
            <ui:define name="contents">
                <h:form>
                    <p:panel header="Change Your password Here, All fields are required!!">
                        <h:form>
                            <p:growl showDetail="true" life="600" autoUpdate="true"/>
                            <h:panelGrid columns="2">
                                <h:outputLabel value="Current Password"/>
                                <p:password value="#{loginManagedBeanController.oldPass}" required="true"/>
                                <h:outputLabel value="New Password"/>
                                <p:password value="#{loginManagedBeanController.newPass}" required="true"/>
                                <h:outputLabel value="Confirm Password"/>
                                <p:password value="#{loginManagedBeanController.confirmPass}" required="true"/>
                                <h:commandButton value="Update Password" action="#{loginManagedBeanController.checkEnteries}"/>
                            </h:panelGrid>
                        </h:form>
                    </p:panel>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Pharmaderm/Pharmaderm-war/web/clear_1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>-clear -page</title>
    </h:head>
    <h:body>
      
        <ui:composition template="user.xhtml">
            <ui:define name="contents">
                <h:form>
                    <p:panel header="Clear Debtors Here by selecting their company name or patient's name">
                        <h:form>
                            <h:panelGrid columns="3">
                                <h:outputLabel value="Company / Customer's Name"/>
                                <p:selectOneMenu value="#{creditAndPaymentController.compnayName}">
                                    <f:selectItem itemLabel="--select one--"/>
                                    <f:selectItems value="#{creditAndPaymentController.creditSelectItems}"/>
                                </p:selectOneMenu>
                                <h:commandButton value="Clear" action="#{creditAndPaymentController.clearCompanies}"/>
                            </h:panelGrid>
                        </h:form>
                    </p:panel>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Pharmaderm/Pharmaderm-war/web/clear_2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>-clear -page</title>
    </h:head>
    <h:body>
     
        <ui:composition template="both.xhtml">
            <ui:define name="contents">
                <h:form>
                    <p:panel header="Clear Debtors Here by selecting their company name or patient's name">
                        <h:form>
                            <h:panelGrid columns="3">
                                <h:outputLabel value="Company / Customer's Name"/>
                                <p:selectOneMenu value="#{creditAndPaymentController.compnayName}">
                                    <f:selectItem itemLabel="--select one--"/>
                                    <f:selectItems value="#{creditAndPaymentController.creditSelectItems}"/>
                                </p:selectOneMenu>
                                <h:commandButton value="Clear" action="#{creditAndPaymentController.clearCompanies}"/>
                            </h:panelGrid>
                        </h:form>
                    </p:panel>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Pharmaderm/Pharmaderm-war/web/patient.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>-patient</title>
    </h:head>
    <h:body>
        <ui:composition template="admin.xhtml">
       
            <ui:define name="contents">
                <h:form>
                    <p:panel header="Please Enter Customers returned drugs here!!">
                        <h:form>
                            <h:panelGrid columns="2">
                                <h:outputLabel value="Drug Name:"/>
                                <p:inputText value="#{stockController.drugsReturned.drugName}" required="true"/>
                                <h:outputLabel value="Quantity:"/>
                                <p:inputText value="#{stockController.drugsReturned.quantity}" required="true"/>
                                <h:outputLabel value="Reason"/>
                                <p:inputTextarea value="#{stockController.drugsReturned.reason}" required="true"/>
                                <h:commandButton value="Save" action="#{stockController.patietntsDrugsSave}"/>
                            </h:panelGrid>
                        </h:form>
                    </p:panel>
                    <f:view>
                        <h:form>
                            <h1><h:outputText value="Drugs Returned By Customers"/></h1>
                            <p:dataTable value="#{stockController.allDrugsByCustomers}" var="item" paginator="true" rows="10">
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Drug Name"/>
                                    </f:facet>
                                    <h:outputText value="#{item.drugName}"/>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        Quantity
                                    </f:facet>
                                    <h:outputText value="#{item.quantity}"/>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Reason"/>
                                    </f:facet>
                                    <h:outputText value="#{item.reason}"/>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Date Returned"/>
                                    </f:facet>
                                    <h:outputText value="#{item.dateReturned}">
                                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                    </h:outputText>
                                </p:column>
                            </p:dataTable>
                        </h:form>
                    </f:view>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Pharmaderm/Pharmaderm-war/web/report.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>-single - drug</title>
    </h:head>
    <h:body>
        <ui:composition template="admin.xhtml">
            <ui:define name="contents">
                <h:form>
                    <p:panel header="Select Drug to generate report by selecting starting and ending dates!!">
                        <h:form>
                            <h:panelGrid columns="7">
                                <h:outputLabel value="Drug Name:"/>
                                <p:selectOneMenu value="#{stockController.drugName}">
                                    <f:selectItem itemLabel="..select drug.."/>
                                    <f:selectItems value="#{stockController.salesSelect}"/>
                                </p:selectOneMenu>
                                <h:outputLabel value="From:"/>
                                <p:calendar value="#{stockController.stDate}" navigator="true" mode="popup" showOn="button"/>
                                <h:outputLabel value="To:"/>
                                <p:calendar value="#{stockController.endDate}" navigator="true" mode="popup" showOn="button"/>
                                <h:commandButton value="Process Report" action="#{stockController.displayInfoPage}"/>
                            </h:panelGrid>
                        </h:form>
                    </p:panel>
                    <f:view>
                        <h:form id="ft">
                            <h1><h:outputText value="Report for Drug, #{stockController.drugName}"/></h1>
                            <p:dataTable value="#{stockController.singleDrugReport}" var="item">
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Drug Name"/>
                                    </f:facet>
                                    <h:outputText value="#{item.drugName}"/>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Drug Quantity"/>
                                    </f:facet>
                                    <h:outputText value="#{item.drugQuantity}"/>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Selling Price Amount"/>
                                    </f:facet>
                                    <h:outputText value="#{item.drugPrice}"/>
                                    <f:facet name="footer">
                                        <h:outputText value="#{stockController.single_amount}" />
                                    </f:facet>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Cost Price Amount"/>
                                    </f:facet>
                                    <h:outputText value="#{item.costAmount}"/>
                                    <f:facet name="footer">
                                        <h:outputText value="#{stockController.single_cost_amount}" />
                                    </f:facet>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Sales Date"/>
                                    </f:facet>
                                    <h:outputText value="#{item.salesDate}">
                                        <f:convertDateTime pattern="MM/dd/yyyy" />
                                    </h:outputText>
                                </p:column>
                                <f:facet name="footer">
                                    <h:outputText value="Profit is: #{stockController.daily_profit}" />
                                </f:facet>
                            </p:dataTable>
                            <p:commandButton value="Print" type="button" icon="ui-icon-print" rendered="#{stockController.print_report}">
                                <p:printer target="ft"/>
                            </p:commandButton>
                        </h:form>
                    </f:view>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>